### PR TITLE
04; fix permit limit

### LINKED ISSUE #4: Specifying identity on startup in config file causes permits to never be updated
Permits get set to the default value (10) if the identity key is specified in the config file on start up. If using setIdentity RPC call instead of specifying at start up the permit gets set correctly.

### PR DESCRIPTION
**Pull request by lvboudre**
Closes #4

### CODE REVIEW

File: src/stake.rs [hunk 1]
```diff
@@ -84,42 +90,38 @@ impl StakeInfo {
...
-                metrics::cluster_identity_stake_set(metrics::ClusterIdentityStakeKind::Jet, stake);
-                metrics::cluster_identity_stake_set(
-                    metrics::ClusterIdentityStakeKind::Total,
-                    total_stake,
-                );
-                metrics::cluster_identity_stake_set(
-                    metrics::ClusterIdentityStakeKind::MaxStreams,
-                    max_streams,
-                );
+            // https://github.com/rpcpool/solana-private/blob/v1.18.18-triton/streamer/src/nonblocking/quic.rs#L780-L790
```
Comment (linuskendall) [inline src/stake.rs:93]: need to update these links to point to either rpcpool/solana-public or to anza-xyz/agave

**Review by linuskendall — APPROVED** [review]
